In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import RandomizedSearchCV
import xgboost as xgb


In [3]:
df1 = pd.read_csv(r'Z:\farrukhabad_Clustered.csv')

In [4]:
df1

X            Y  Cluster Class
0         3920216.550  4404483.732       19   NaN
1         3920225.799  4404483.732       19   NaN
2         3920198.053  4404474.483       19   NaN
3         3920207.302  4404474.483       19   NaN
4         3920216.550  4404474.483       19   NaN
...               ...          ...      ...   ...
22085441  3957258.653  4343190.845        5   NaN
22085442  3957267.902  4343190.845        5   NaN
22085443  3957277.151  4343190.845        5   NaN
22085444  3957286.400  4343190.845        5   NaN
22085445  3957295.648  4343190.845        9   NaN

[22085446 rows x 4 columns]

In [5]:
df2 = pd.read_csv(r'Z:\Farrukhabad.csv')

In [6]:
x= df1[['Cluster']]

In [7]:
df= df2.join(x)

In [9]:
df.head(6)

Geo_X        Geo_Y  Band_1  Band_2  Band_3  Band_4  Band_5  Band_6  \
0  3920216.550  4404483.732    2699    2465    2445    2372    2545    3198   
1  3920225.799  4404483.732    2699    2531    2506    2508    2545    3198   
2  3920198.053  4404474.483    2699    2416    2420    2279    2505    3329   
3  3920207.302  4404474.483    2699    2471    2433    2357    2505    3329   
4  3920216.550  4404474.483    2699    2476    2469    2408    2545    3198   
5  3920225.799  4404474.483    2699    2485    2488    2458    2545    3198   

   Band_7  Band_8  Band_9  Band_10  Band_11  Band_12  Band_13  Cluster  
0    3644    3291    1281     1010     3594     2824     3771       19  
1    3644    3276    1281     1010     3594     2824     3771       19  
2    3784    3556    1281     1010     3500     2642     3959       19  
3    3784    3464    1281     1010     3500     2642     3959       19  
4    3644    3340    1281     1010     3594     2824     3771       19  
5    3644    3307    1281     1010     3594     2824     3771       19

In [10]:
df['Cluster'].unique()

array([19,  5,  9,  2, 13, 11,  6,  0,  7,  4, 10, 20,  1, 17, 15, 18,  8,
        3, 16, 14, 12], dtype=int64)

In [50]:
df['Cluster'] = df['Cluster'].replace(20,0)

In [52]:
df['Cluster'].unique()

array([0, 1], dtype=int64)

In [53]:
df.rename(columns = {'Cluster':'maize_mask_farrukhabad'},inplace=True)

In [54]:
df

Geo_X        Geo_Y  Band_1  Band_2  Band_3  Band_4  Band_5  \
0         3920216.550  4404483.732    2699    2465    2445    2372    2545   
1         3920225.799  4404483.732    2699    2531    2506    2508    2545   
2         3920198.053  4404474.483    2699    2416    2420    2279    2505   
3         3920207.302  4404474.483    2699    2471    2433    2357    2505   
4         3920216.550  4404474.483    2699    2476    2469    2408    2545   
...               ...          ...     ...     ...     ...     ...     ...   
22085441  3957258.653  4343190.845    2667    2475    2462    2498    2489   
22085442  3957267.902  4343190.845    2667    2521    2531    2594    2489   
22085443  3957277.151  4343190.845    2656    2601    2603    2713    2601   
22085444  3957286.400  4343190.845    2656    2571    2595    2623    2601   
22085445  3957295.648  4343190.845    2656    2535    2573    2596    2578   

          Band_6  Band_7  Band_8  Band_9  Band_10  Band_11  Band_12  Band_13  \
0           3198    3644    3291    1281     1010     3594     2824     3771   
1           3198    3644    3276    1281     1010     3594     2824     3771   
2           3329    3784    3556    1281     1010     3500     2642     3959   
3           3329    3784    3464    1281     1010     3500     2642     3959   
4           3198    3644    3340    1281     1010     3594     2824     3771   
...          ...     ...     ...     ...      ...      ...      ...      ...   
22085441    2854    3177    2970    1210     1015     3580     2760     3339   
22085442    2854    3177    3038    1210     1015     3580     2760     3339   
22085443    3011    3392    3226    1219     1015     3700     2879     3601   
22085444    3011    3392    3308    1219     1015     3700     2879     3601   
22085445    3166    3588    3301    1219     1015     3687     2753     3784   

          maize_mask_farrukhabad  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  
...                          ...  
22085441                       0  
22085442                       0  
22085443                       0  
22085444                       0  
22085445                       0  

[22085446 rows x 16 columns]

In [55]:
df['maize_mask_farrukhabad'].unique()

array([0, 1], dtype=int64)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22085446 entries, 0 to 22085445
Data columns (total 16 columns):
 #   Column                  Dtype  
---  ------                  -----  
 0   Geo_X                   float64
 1   Geo_Y                   float64
 2   Band_1                  int64  
 3   Band_2                  int64  
 4   Band_3                  int64  
 5   Band_4                  int64  
 6   Band_5                  int64  
 7   Band_6                  int64  
 8   Band_7                  int64  
 9   Band_8                  int64  
 10  Band_9                  int64  
 11  Band_10                 int64  
 12  Band_11                 int64  
 13  Band_12                 int64  
 14  Band_13                 int64  
 15  maize_mask_farrukhabad  int64  
dtypes: float64(2), int64(14)
memory usage: 2.6 GB


In [56]:
x=df[['Band_3','Band_4','Band_8']]
y=df['maize_mask_farrukhabad']

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=51)

# rfc_model

In [58]:
%%time
rfc_model = RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=15)
rfc_model.fit(X_train,Y_train)
rfc_train_pred = rfc_model.predict(X_train)
rfc_test_pred = rfc_model.predict(X_test)
print(f1_score(Y_train,rfc_train_pred))
print(f1_score(Y_test,rfc_test_pred))
print("training score on 20% data")

0.6582741460699599
0.6507783885160444
training score on 20% data
Wall time: 22min 24s


In [65]:
%%time
rfc_model = RandomForestClassifier(n_estimators=80,criterion='gini',max_depth=15)
rfc_model.fit(X_train,Y_train)
rfc_train_pred = rfc_model.predict(X_train)
rfc_test_pred = rfc_model.predict(X_test)
print(f1_score(Y_train,rfc_train_pred))
print(f1_score(Y_test,rfc_test_pred))
print("training score on 80% data")

0.6532107247106724
0.6505209026291942
training score on 80% data
Wall time: 56min


In [59]:
%%time
dtc = DecisionTreeClassifier(criterion='gini',max_depth= 20,random_state=60,min_samples_split=2)
dtc.fit(X_train,Y_train)
dtc_train_pred = dtc.predict(X_train)
dtc_test_pred = dtc.predict(X_test)
print(f1_score(Y_train,dtc_train_pred))
print(f1_score(Y_test,dtc_test_pred))
print("training score on 20% data")

0.7113745798090904
0.6455583609955872
training score on 20% data
Wall time: 43.1 s


In [63]:
%%time
dtc = DecisionTreeClassifier(criterion='gini',max_depth= 20,random_state=60)
dtc.fit(X_train,Y_train)
dtc_train_pred = dtc.predict(X_train)
dtc_test_pred = dtc.predict(X_test)
print(f1_score(Y_train,dtc_train_pred))
print(f1_score(Y_test,dtc_test_pred))
print("training score on 80% data")

0.6884897123634319
0.6600220292335687
training score on 80% data
Wall time: 2min 3s


In [69]:
dtc_model = DecisionTreeClassifier()

In [ ]:
parameter = {'criterion':['gini', 'entropy', 'log_loss'],'max_depth':[8,10,12,15,20],}

In [60]:
%%time
xgbc = xgb.XGBClassifier(n_estimators=70,random_state=55,max_depth=15)
xgbc.fit(X_train,Y_train)
xgbc_train_pred = xgbc.predict(X_train)
xgbc_test_pred = xgbc.predict(X_test)
print(f1_score(Y_train,xgbc_train_pred))
print(f1_score(Y_test,xgbc_test_pred))
print("training score on 20% data")

0.6806591481468554
0.6600860827185108
training score on 20% data
Wall time: 1min 53s


In [64]:
%%time
xgbc = xgb.XGBClassifier(n_estimators=70,random_state=55,max_depth=15)
xgbc.fit(X_train,Y_train)
xgbc_train_pred = xgbc.predict(X_train)
xgbc_test_pred = xgbc.predict(X_test)
print(f1_score(Y_train,xgbc_train_pred))
print(f1_score(Y_test,xgbc_test_pred))
print("training score on 80% data")

0.6698166186394694
0.6626436851916456
training score on 80% data
Wall time: 6min 36s


In [69]:
import joblib

In [70]:
joblib.dump(xgbc,'xgb_model_mainpuri.pkl')

['xgb_model_mainpuri.pkl']

In [73]:
xgb_load_model = joblib.load('xgb_model_mainpuri.pkl')

In [90]:
data = pd.read_csv(r'Z:\temp\Etah.csv')

In [95]:
data.head(2)

Geo_X        Geo_Y  Band_1  Band_2  Band_3  Band_4  Band_5  Band_6  \
0  3859505.626  4412341.437    2419    2173    2127    1941    2188    3487   
1  3859514.557  4412341.437    2492    2171    2147    1933    2177    3404   

   Band_7  Band_8  Band_9  Band_10  Band_11  Band_12  Band_13  
0    4214    3948    1420     1010     3287     2141     4556  
1    4140    3951    1396     1010     3423     2227     4462

In [96]:
data.columns

Index(['Geo_X', 'Geo_Y', 'Band_1', 'Band_2', 'Band_3', 'Band_4', 'Band_5',
       'Band_6', 'Band_7', 'Band_8', 'Band_9', 'Band_10', 'Band_11', 'Band_12',
       'Band_13'],
      dtype='object')

In [98]:
x = data[['Band_3','Band_4','Band_8']]

In [99]:
x

Band_3  Band_4  Band_8
0           2127    1941    3948
1           2147    1933    3951
2           2147    1933    3951
3           2136    2005    3850
4           2216    2114    3818
...          ...     ...     ...
26237601    2303    2142    4103
26237602    2303    2139    4056
26237603    2184    1920    4413
26237604    2178    1918    4612
26237605    2155    1850    4692

[26237606 rows x 3 columns]

In [101]:
Etah_pred = xgb_load_model.predict(x)

In [103]:
data['prediction']=Etah_pred

In [105]:
data.to_csv('Etah_prediction.csv')