In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import RandomizedSearchCV
import xgboost as xgb

In [83]:
df1 = pd.read_csv(r'Z:\Mainpuri.csv')

In [85]:
df1

Geo_X        Geo_Y  Band_1  Band_2  Band_3  Band_4  Band_5  \
0         3892066.488  4377425.758    2581    2489    2466    2411    2671   
1         3892075.621  4377425.758    2581    2395    2377    2184    2302   
2         3892084.754  4377425.758    2581    2251    2155    1944    2302   
3         3892093.887  4377425.758    2496    2163    2064    1753    2070   
4         3892103.020  4377425.758    2496    2165    2079    1740    2009   
...               ...          ...     ...     ...     ...     ...     ...   
26395921  3902898.214  4320974.751    2394    2112    1989    1643    1852   
26395922  3902907.347  4320974.751    2394    2100    1990    1632    1852   
26395923  3902916.480  4320974.751    2394    2084    1990    1608    1844   
26395924  3902925.612  4320974.751    2394    2105    1992    1604    1844   
26395925  3902934.745  4320974.751    2394    2105    1992    1604    1844   

          Band_6  Band_7  Band_8  Band_9  Band_10  Band_11  Band_12  Band_13  
0           3681    4335    3759    1334     1010     3215     2403     4464  
1           3307    4010    3796    1334     1010     2923     2047     4234  
2           3307    4010    3770    1334     1010     2923     2047     4234  
3           3441    4322    4063    1352     1010     2696     1758     4577  
4           3514    4506    4299    1352     1010     2751     1762     4770  
...          ...     ...     ...     ...      ...      ...      ...      ...  
26395921    2981    3752    3263    1228     1008     2121     1480     3823  
26395922    2981    3752    3664    1228     1008     2121     1480     3823  
26395923    3239    4191    3959    1228     1008     2289     1523     4346  
26395924    3239    4191    3969    1228     1008     2289     1523     4346  
26395925    3239    4191    3969    1228     1008     2289     1523     4346  

[26395926 rows x 15 columns]

In [86]:
df2 = pd.read_csv(r'Z:\mainpuri_Clustered.csv')

In [87]:
df2

X            Y  Cluster  Class
0         3892066.488  4377425.758        5    NaN
1         3892075.621  4377425.758        3  Bajra
2         3892084.754  4377425.758        3  Bajra
3         3892093.887  4377425.758        6  Maize
4         3892103.020  4377425.758        6  Maize
...               ...          ...      ...    ...
26395921  3902898.214  4320974.751        0   Rice
26395922  3902907.347  4320974.751        0   Rice
26395923  3902916.480  4320974.751        0   Rice
26395924  3902925.612  4320974.751        0   Rice
26395925  3902934.745  4320974.751        0   Rice

[26395926 rows x 4 columns]

In [88]:
x= df2[['Cluster']]

In [89]:
df= df1.join(x)

In [91]:
df.head(6)

Geo_X        Geo_Y  Band_1  Band_2  Band_3  Band_4  Band_5  Band_6  \
0  3892066.488  4377425.758    2581    2489    2466    2411    2671    3681   
1  3892075.621  4377425.758    2581    2395    2377    2184    2302    3307   
2  3892084.754  4377425.758    2581    2251    2155    1944    2302    3307   
3  3892093.887  4377425.758    2496    2163    2064    1753    2070    3441   
4  3892103.020  4377425.758    2496    2165    2079    1740    2009    3514   
5  3892112.153  4377425.758    2496    2175    2090    1744    2009    3514   

   Band_7  Band_8  Band_9  Band_10  Band_11  Band_12  Band_13  Cluster  
0    4335    3759    1334     1010     3215     2403     4464        5  
1    4010    3796    1334     1010     2923     2047     4234        3  
2    4010    3770    1334     1010     2923     2047     4234        3  
3    4322    4063    1352     1010     2696     1758     4577        6  
4    4506    4299    1352     1010     2751     1762     4770        6  
5    4506    4374    1352     1010     2751     1762     4770        6

In [94]:
df['Cluster'].unique()

array([5, 3, 6, 4, 7, 2, 8, 1, 0], dtype=int64)

In [107]:
df['Cluster'] = df['Cluster'].replace(8,0)


In [109]:
df['Cluster'].unique()

array([0, 1], dtype=int64)

In [110]:
df.rename(columns = {'Cluster':'maize_mask_mainpuri'},inplace=True)

In [111]:
df

Geo_X        Geo_Y  Band_1  Band_2  Band_3  Band_4  Band_5  \
0         3892066.488  4377425.758    2581    2489    2466    2411    2671   
1         3892075.621  4377425.758    2581    2395    2377    2184    2302   
2         3892084.754  4377425.758    2581    2251    2155    1944    2302   
3         3892093.887  4377425.758    2496    2163    2064    1753    2070   
4         3892103.020  4377425.758    2496    2165    2079    1740    2009   
...               ...          ...     ...     ...     ...     ...     ...   
26395921  3902898.214  4320974.751    2394    2112    1989    1643    1852   
26395922  3902907.347  4320974.751    2394    2100    1990    1632    1852   
26395923  3902916.480  4320974.751    2394    2084    1990    1608    1844   
26395924  3902925.612  4320974.751    2394    2105    1992    1604    1844   
26395925  3902934.745  4320974.751    2394    2105    1992    1604    1844   

          Band_6  Band_7  Band_8  Band_9  Band_10  Band_11  Band_12  Band_13  \
0           3681    4335    3759    1334     1010     3215     2403     4464   
1           3307    4010    3796    1334     1010     2923     2047     4234   
2           3307    4010    3770    1334     1010     2923     2047     4234   
3           3441    4322    4063    1352     1010     2696     1758     4577   
4           3514    4506    4299    1352     1010     2751     1762     4770   
...          ...     ...     ...     ...      ...      ...      ...      ...   
26395921    2981    3752    3263    1228     1008     2121     1480     3823   
26395922    2981    3752    3664    1228     1008     2121     1480     3823   
26395923    3239    4191    3959    1228     1008     2289     1523     4346   
26395924    3239    4191    3969    1228     1008     2289     1523     4346   
26395925    3239    4191    3969    1228     1008     2289     1523     4346   

          maize_mask_mainpuri  
0                           0  
1                           0  
2                           0  
3                           0  
4                           0  
...                       ...  
26395921                    0  
26395922                    0  
26395923                    0  
26395924                    0  
26395925                    0  

[26395926 rows x 16 columns]

In [112]:
df['maize_mask_mainpuri'].unique()

array([0, 1], dtype=int64)

In [113]:
x=df[['Band_3','Band_4','Band_8']]
y=df['maize_mask_mainpuri']

In [120]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=51)

# rfc_model

In [119]:
%%time
rfc_model = RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=15)
rfc_model.fit(X_train,Y_train)
rfc_train_pred = rfc_model.predict(X_train)
rfc_test_pred = rfc_model.predict(X_test)
print(f1_score(Y_train,rfc_train_pred))
print(f1_score(Y_test,rfc_test_pred))
print("training score on 20% data")

0.7355055948107686
0.7285103615406273
training score on 20% data
Wall time: 25min 14s


In [ ]:
%%time
rfc_model = RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=15)
rfc_model.fit(X_train,Y_train)
rfc_train_pred = rfc_model.predict(X_train)
rfc_test_pred = rfc_model.predict(X_test)
print(f1_score(Y_train,rfc_train_pred))
print(f1_score(Y_test,rfc_test_pred))
print("training score on 80% data")

In [117]:
%%time
dtc = DecisionTreeClassifier(criterion='gini',max_depth= 20,random_state=60,min_samples_split=2)
dtc.fit(X_train,Y_train)
dtc_train_pred = dtc.predict(X_train)
dtc_test_pred = dtc.predict(X_test)
print(f1_score(Y_train,dtc_train_pred))
print(f1_score(Y_test,dtc_test_pred))
print("training score on 20% data")

0.771909126840366
0.7217566416518907
training score on 20% data
Wall time: 48.8 s


In [122]:
%%time
dtc = DecisionTreeClassifier(criterion='gini',max_depth= 20,random_state=60,min_samples_split=2)
dtc.fit(X_train,Y_train)
dtc_train_pred = dtc.predict(X_train)
dtc_test_pred = dtc.predict(X_test)
print(f1_score(Y_train,dtc_train_pred))
print(f1_score(Y_test,dtc_test_pred))
print("training score on 80% data")

0.7545169738724885
0.733457848701832
training score on 80% data
Wall time: 2min 21s


In [118]:
%%time
xgbc = xgb.XGBClassifier(n_estimators=70,random_state=55,max_depth=15)
xgbc.fit(X_train,Y_train)
xgbc_train_pred = xgbc.predict(X_train)
xgbc_test_pred = xgbc.predict(X_test)
print(f1_score(Y_train,xgbc_train_pred))
print(f1_score(Y_test,xgbc_test_pred))
print("training score on 20% data")

0.7518518741153455
0.7337198844376942
training score on 20% data
Wall time: 2min 17s


In [121]:
%%time
xgbc = xgb.XGBClassifier(n_estimators=70,random_state=55,max_depth=15)
xgbc.fit(X_train,Y_train)
xgbc_train_pred = xgbc.predict(X_train)
xgbc_test_pred = xgbc.predict(X_test)
print(f1_score(Y_train,xgbc_train_pred))
print(f1_score(Y_test,xgbc_test_pred))
print("training score on 80% data")

0.7427604161465483
0.7364102150577566
training score on 80% data
Wall time: 10min 30s


In [69]:
import joblib

In [70]:
joblib.dump(xgbc,'xgb_model_mainpuri.pkl')

['xgb_model_mainpuri.pkl']

In [73]:
xgb_load_model = joblib.load('xgb_model_mainpuri.pkl')

In [90]:
data = pd.read_csv(r'Z:\temp\Etah.csv')

In [95]:
data.head(2)

Geo_X        Geo_Y  Band_1  Band_2  Band_3  Band_4  Band_5  Band_6  \
0  3859505.626  4412341.437    2419    2173    2127    1941    2188    3487   
1  3859514.557  4412341.437    2492    2171    2147    1933    2177    3404   

   Band_7  Band_8  Band_9  Band_10  Band_11  Band_12  Band_13  
0    4214    3948    1420     1010     3287     2141     4556  
1    4140    3951    1396     1010     3423     2227     4462

In [96]:
data.columns

Index(['Geo_X', 'Geo_Y', 'Band_1', 'Band_2', 'Band_3', 'Band_4', 'Band_5',
       'Band_6', 'Band_7', 'Band_8', 'Band_9', 'Band_10', 'Band_11', 'Band_12',
       'Band_13'],
      dtype='object')

In [98]:
x = data[['Band_3','Band_4','Band_8']]

In [99]:
x

Band_3  Band_4  Band_8
0           2127    1941    3948
1           2147    1933    3951
2           2147    1933    3951
3           2136    2005    3850
4           2216    2114    3818
...          ...     ...     ...
26237601    2303    2142    4103
26237602    2303    2139    4056
26237603    2184    1920    4413
26237604    2178    1918    4612
26237605    2155    1850    4692

[26237606 rows x 3 columns]

In [101]:
Etah_pred = xgb_load_model.predict(x)

In [103]:
data['prediction']=Etah_pred

In [105]:
data.to_csv('Etah_prediction.csv')